---
- hosts: all
  become: true
  vars:
    new_hostname: "n8nserv"

  tasks:
    - name: Set hostname (hostnamectl)
      hostname:
        name: "{{new_hostname}}"
    - name: Reboot machine
      reboot:
